/**
 * Loads base weight tables and applies data-derived overrides from weight-overrides.json.
 *
 * The override file is generated by `npm run calibrate` and checked into git.
 * If the file is missing or empty, base weights from consonants.js / vowels.js / clusters.js
 * are used unchanged.
 */
import { readFileSync } from 'node:fs';
import { CONSONANTS as BASE_CONSONANTS } from './consonants.js';
import { VOWEL_PATTERNS as BASE_VOWEL_PATTERNS } from './vowels.js';
import { THOR_SO_VARIANTS as BASE_THOR_SO, SOR_RO_VARIANTS as BASE_SOR_RO } from './clusters.js';

// Try to load overrides; graceful fallback if missing
let overrides = null;
try {
  const raw = readFileSync(new URL('./weight-overrides.json', import.meta.url), 'utf-8');
  overrides = JSON.parse(raw);
} catch {
  // No overrides file or invalid JSON — use base weights
}

/**
 * Deep-clone a variant array and apply weight overrides.
 * @param {Array<{text: string, weight: number}>} variants - base variants
 * @param {Object<string, number>} overrideMap - { variantText: newWeight }
 * @returns {Array<{text: string, weight: number}>}
 */
function applyVariantOverrides(variants, overrideMap) {
  if (!overrideMap || Object.keys(overrideMap).length === 0) return variants;
  return variants.map(v => {
    const override = overrideMap[v.text];
    return override !== undefined ? { text: v.text, weight: override } : v;
  });
}

/**
 * Apply consonant overrides to the base consonant table.
 */
function buildConsonants() {
  const consonantOverrides = overrides?.consonants;
  if (!consonantOverrides || Object.keys(consonantOverrides).length === 0) {
    return BASE_CONSONANTS;
  }

  const result = {};
  for (const [char, entry] of Object.entries(BASE_CONSONANTS)) {
    const charOverride = consonantOverrides[char];
    if (!charOverride) {
      result[char] = entry;
      continue;
    }
    result[char] = {
      ...entry,
      initial: applyVariantOverrides(entry.initial, charOverride.initial),
      final: applyVariantOverrides(entry.final, charOverride.final),
    };
  }
  return result;
}

/**
 * Apply vowel overrides to the base vowel pattern table.
 */
function buildVowelPatterns() {
  const vowelOverrides = overrides?.vowels;
  if (!vowelOverrides || Object.keys(vowelOverrides).length === 0) {
    return BASE_VOWEL_PATTERNS;
  }

  const result = {};
  for (const [id, entry] of Object.entries(BASE_VOWEL_PATTERNS)) {
    const patternOverride = vowelOverrides[id];
    if (!patternOverride) {
      result[id] = entry;
      continue;
    }
    result[id] = {
      ...entry,
      variants: applyVariantOverrides(entry.variants, patternOverride),
    };
  }
  return result;
}

/**
 * Apply cluster overrides to a special cluster variant array.
 */
function buildClusterVariants(baseVariants, clusterKey) {
  const clusterOverrides = overrides?.clusters?.[clusterKey];
  if (!clusterOverrides || Object.keys(clusterOverrides).length === 0) {
    return baseVariants;
  }
  return applyVariantOverrides(baseVariants, clusterOverrides);
}

export const CONSONANTS = buildConsonants();
export const VOWEL_PATTERNS = buildVowelPatterns();
export const THOR_SO_VARIANTS = buildClusterVariants(BASE_THOR_SO, 'ทร');
export const SOR_RO_VARIANTS = buildClusterVariants(BASE_SOR_RO, 'ศร');
