/**
 * Loads base weight tables and applies data-derived overrides from weight-overrides.json.
 *
 * The override file is generated by `npm run calibrate` and checked into git.
 * If the file is missing or empty, base weights from consonants.js / vowels.js / clusters.js
 * are used unchanged.
 */
import { readFileSync } from 'node:fs';
import { CONSONANTS as BASE_CONSONANTS } from './consonants.js';
import { VOWEL_PATTERNS as BASE_VOWEL_PATTERNS } from './vowels.js';
import { THOR_SO_VARIANTS as BASE_THOR_SO, SOR_RO_VARIANTS as BASE_SOR_RO } from './clusters.js';

// Try to load overrides; graceful fallback if missing
let overrides = null;
try {
  const raw = readFileSync(new URL('./weight-overrides.json', import.meta.url), 'utf-8');
  overrides = JSON.parse(raw);
} catch {
  // No overrides file or invalid JSON — use base weights
}

/**
 * Deep-clone a variant array and apply weight overrides.
 * @param {Array<{text: string, weight: number}>} variants - base variants
 * @param {Object<string, number>} overrideMap - { variantText: newWeight }
 * @returns {Array<{text: string, weight: number}>}
 */
function applyVariantOverrides(variants, overrideMap) {
  if (!overrideMap || Object.keys(overrideMap).length === 0) return variants;
  return variants.map(v => {
    const override = overrideMap[v.text];
    return override !== undefined ? { text: v.text, weight: override } : v;
  });
}

/**
 * Append data-discovered new variants to an existing variant array.
 * Only adds variants whose text doesn't already exist.
 * @param {Array<{text: string, weight: number}>} variants - existing variants
 * @param {Object<string, number>} newVariantMap - { variantText: weight }
 * @returns {Array<{text: string, weight: number}>}
 */
function applyNewVariants(variants, newVariantMap) {
  if (!newVariantMap || Object.keys(newVariantMap).length === 0) return variants;
  const existing = new Set(variants.map(v => v.text));
  const additions = [];
  for (const [text, weight] of Object.entries(newVariantMap)) {
    if (!existing.has(text)) {
      additions.push({ text, weight });
    }
  }
  return additions.length > 0 ? [...variants, ...additions] : variants;
}

/**
 * Apply consonant overrides to the base consonant table.
 */
function buildConsonants() {
  const consonantOverrides = overrides?.consonants;
  const newConsonants = overrides?.newVariants?.consonants;
  const hasOverrides = consonantOverrides && Object.keys(consonantOverrides).length > 0;
  const hasNew = newConsonants && Object.keys(newConsonants).length > 0;

  if (!hasOverrides && !hasNew) return BASE_CONSONANTS;

  const result = {};
  for (const [char, entry] of Object.entries(BASE_CONSONANTS)) {
    const charOverride = consonantOverrides?.[char];
    const charNew = newConsonants?.[char];
    if (!charOverride && !charNew) {
      result[char] = entry;
      continue;
    }
    let initial = applyVariantOverrides(entry.initial, charOverride?.initial);
    let final = applyVariantOverrides(entry.final, charOverride?.final);
    initial = applyNewVariants(initial, charNew?.initial);
    final = applyNewVariants(final, charNew?.final);
    result[char] = { ...entry, initial, final };
  }
  return result;
}

/**
 * Apply vowel overrides to the base vowel pattern table.
 */
function buildVowelPatterns() {
  const vowelOverrides = overrides?.vowels;
  const newVowels = overrides?.newVariants?.vowels;
  const hasOverrides = vowelOverrides && Object.keys(vowelOverrides).length > 0;
  const hasNew = newVowels && Object.keys(newVowels).length > 0;

  if (!hasOverrides && !hasNew) return BASE_VOWEL_PATTERNS;

  const result = {};
  for (const [id, entry] of Object.entries(BASE_VOWEL_PATTERNS)) {
    const patternOverride = vowelOverrides?.[id];
    const patternNew = newVowels?.[id];
    if (!patternOverride && !patternNew) {
      result[id] = entry;
      continue;
    }
    let variants = applyVariantOverrides(entry.variants, patternOverride);
    variants = applyNewVariants(variants, patternNew);
    result[id] = { ...entry, variants };
  }
  return result;
}

/**
 * Apply cluster overrides to a special cluster variant array.
 */
function buildClusterVariants(baseVariants, clusterKey) {
  const clusterOverrides = overrides?.clusters?.[clusterKey];
  const clusterNew = overrides?.newVariants?.clusters?.[clusterKey];
  let result = applyVariantOverrides(baseVariants, clusterOverrides);
  result = applyNewVariants(result, clusterNew);
  return result;
}

export const CONSONANTS = buildConsonants();
export const VOWEL_PATTERNS = buildVowelPatterns();
export const THOR_SO_VARIANTS = buildClusterVariants(BASE_THOR_SO, 'ทร');
// ทร mid-word (อินทรา, จันทร์) is never pronounced "s" — filter it out
export const THOR_SO_VARIANTS_MEDIAL = THOR_SO_VARIANTS.filter(v => v.text !== 's');
export const SOR_RO_VARIANTS = buildClusterVariants(BASE_SOR_RO, 'ศร');
