/**
 * Dictionary lookup for known Thai↔Latin mappings.
 *
 * Loads two dictionary files:
 * - dictionary.json — auto-generated transliterations (regenerated by calibrate)
 * - dictionary-manual.json — hand-curated translations/overrides (NOT regenerated)
 *
 * Manual entries take precedence on collision. Both files are optional.
 */
import { readFileSync } from 'node:fs';

// Manual entries are hand-curated overrides (Bangkok, Suvarnabhumi, etc.)
// They must always outrank both algorithmic (1.0) and data-derived (up to 1.1) weights.
const MANUAL_WEIGHT = 1.5;

let dict = null;
let loaded = false;

function loadJsonEntries(url) {
  try {
    const raw = readFileSync(new URL(url, import.meta.url), 'utf-8');
    return JSON.parse(raw).entries || {};
  } catch {
    return {};
  }
}

function loadDictionary() {
  if (loaded) return dict;
  loaded = true;

  const auto = loadJsonEntries('./tables/dictionary.json');
  const manual = loadJsonEntries('./tables/dictionary-manual.json');

  // Merge: start with auto, overlay manual entries (manual always wins)
  dict = { ...auto };
  for (const [thai, variants] of Object.entries(manual)) {
    const boosted = variants.map(v => ({ ...v, weight: MANUAL_WEIGHT }));
    const existing = dict[thai];
    if (!existing) {
      dict[thai] = boosted;
      continue;
    }
    // Merge variants: manual takes precedence on text collision
    const map = new Map();
    for (const v of existing) {
      map.set(v.text.toLowerCase(), v);
    }
    for (const v of boosted) {
      map.set(v.text.toLowerCase(), v);
    }
    dict[thai] = [...map.values()];
  }

  if (Object.keys(dict).length === 0) dict = null;
  return dict;
}

/**
 * Look up a Thai word in the dictionary.
 *
 * @param {string} thai - Thai word to look up
 * @returns {Array<{text: string, weight: number}>|null} variants or null if not found
 */
export function lookupWord(thai) {
  const d = loadDictionary();
  if (!d) return null;
  return d[thai] || null;
}
