/**
 * Dictionary lookup for known Thai↔Latin mappings.
 *
 * Loads two dictionary files:
 * - dictionary.json — auto-generated transliterations (regenerated by calibrate)
 * - dictionary-manual.json — hand-curated translations/overrides (NOT regenerated)
 *
 * Manual entries take precedence on collision. Both files are optional.
 */
import { readFileSync } from 'node:fs';

let dict = null;
let loaded = false;

function loadJsonEntries(url) {
  try {
    const raw = readFileSync(new URL(url, import.meta.url), 'utf-8');
    return JSON.parse(raw).entries || {};
  } catch {
    return {};
  }
}

function loadDictionary() {
  if (loaded) return dict;
  loaded = true;

  const auto = loadJsonEntries('./tables/dictionary.json');
  const manual = loadJsonEntries('./tables/dictionary-manual.json');

  // Merge: start with auto, overlay manual entries (manual always wins)
  dict = { ...auto };
  for (const [thai, variants] of Object.entries(manual)) {
    const boosted = variants.map(v => ({
      text: v.text,
      weight: v.weight ?? 1.5,
      type: v.type ?? 'phonetic',
    }));
    const existing = dict[thai];
    if (!existing) {
      dict[thai] = boosted;
      continue;
    }
    // Merge variants: manual takes precedence on text collision
    const map = new Map();
    for (const v of existing) {
      map.set(v.text.toLowerCase(), v);
    }
    for (const v of boosted) {
      map.set(v.text.toLowerCase(), v);
    }
    dict[thai] = [...map.values()];
  }

  if (Object.keys(dict).length === 0) dict = null;
  return dict;
}

/**
 * Look up a Thai word in the dictionary.
 *
 * @param {string} thai - Thai word to look up
 * @param {object} [options]
 * @param {boolean} [options.translations] - Set to false to exclude translation entries (e.g. "bangkok", "thailand")
 * @returns {Array<{text: string, weight: number, type?: string}>|null} variants or null if not found
 */
export function lookupWord(thai, options = {}) {
  const d = loadDictionary();
  if (!d) return null;
  let entries = d[thai] || null;
  if (entries && options.translations === false) {
    entries = entries.filter(e => e.type !== 'translation');
    if (entries.length === 0) return null;
  }
  return entries;
}
